package com.ruoyi.lottery.service;
import com.baomidou.mybatisplus.core.toolkit.IdWorker;import com.ruoyi.common.core.redis.RedisCache;import com.ruoyi.lottery.mapper.LotteryPortalMapper;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.web.client.RestTemplate;import java.net.URLEncoder;import java.nio.charset.StandardCharsets;import java.security.SecureRandom;import java.util.*;import java.util.concurrent.TimeUnit;
@Service public class WechatService {
 @Value("${lottery.wechat.app-id:}")String appId;@Value("${lottery.wechat.app-secret:}")String secret;@Value("${lottery.wechat.require-follow:false}")boolean requireFollow;@Value("${lottery.public-base-url:}")String base;
 private final RedisCache redis;private final LotteryPortalMapper mapper;private final RestTemplate http=new RestTemplate();private final SecureRandom random=new SecureRandom();
 public WechatService(RedisCache r,LotteryPortalMapper m){redis=r;mapper=m;}public boolean configured(){return !appId.isEmpty()&&!secret.isEmpty()&&base.startsWith("https://");}
 public String authorizeUrl(String target){assertConfigured();String callback=base+"/lottery/wechat/callback";return "https://open.weixin.qq.com/connect/oauth2/authorize?appid="+enc(appId)+"&redirect_uri="+enc(callback)+"&response_type=code&scope=snsapi_userinfo&state="+enc(target==null?"/":target)+"#wechat_redirect";}
 @SuppressWarnings("unchecked") public Map<String,Object> authenticate(String code){assertConfigured();Map<String,Object> token=get("https://api.weixin.qq.com/sns/oauth2/access_token?appid="+enc(appId)+"&secret="+enc(secret)+"&code="+enc(code)+"&grant_type=authorization_code");fail(token);String openid=String.valueOf(token.get("openid"));Map<String,Object> profile=get("https://api.weixin.qq.com/sns/userinfo?access_token="+enc(String.valueOf(token.get("access_token")))+"&openid="+enc(openid)+"&lang=zh_CN");fail(profile);boolean subscribed=false;try{Map<String,Object> follow=get("https://api.weixin.qq.com/cgi-bin/user/info?access_token="+enc(globalToken())+"&openid="+enc(openid)+"&lang=zh_CN");subscribed=number(follow.get("subscribe"))==1;}catch(Exception ignored){}if(requireFollow&&!subscribed)throw new IllegalStateException("请先关注公众号后再参与活动");Map<String,Object> user=mapper.userByOpenid(openid);String union=value(profile,"unionid"),nickname=value(profile,"nickname"),avatar=value(profile,"headimgurl");if(user==null){long id=IdWorker.getId();mapper.insertWechatUser(id,openid,union,nickname,avatar,subscribed);user=mapper.userById(id);}else{mapper.updateWechatUser(openid,union,nickname,avatar,subscribed);user=mapper.userByOpenid(openid);}return user;}
 public Map<String,Object> jsConfig(String url){assertConfigured();String nonce=Long.toHexString(random.nextLong()),canonical=WechatSignature.canonicalUrl(url);long timestamp=System.currentTimeMillis()/1000;String source="jsapi_ticket="+ticket()+"&noncestr="+nonce+"&timestamp="+timestamp+"&url="+canonical;Map<String,Object> r=new LinkedHashMap<>();r.put("appId",appId);r.put("timestamp",timestamp);r.put("nonceStr",nonce);r.put("signature",WechatSignature.sign(source));return r;}
 private String globalToken(){String k="lottery:wechat:access-token";String v=redis.getCacheObject(k);if(v!=null)return v;Map<String,Object> r=get("https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid="+enc(appId)+"&secret="+enc(secret));fail(r);v=value(r,"access_token");redis.setCacheObject(k,v,7000,TimeUnit.SECONDS);return v;}private String ticket(){String k="lottery:wechat:js-ticket";String v=redis.getCacheObject(k);if(v!=null)return v;Map<String,Object> r=get("https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token="+enc(globalToken())+"&type=jsapi");fail(r);v=value(r,"ticket");redis.setCacheObject(k,v,7000,TimeUnit.SECONDS);return v;}
 @SuppressWarnings("unchecked")private Map<String,Object>get(String u){return http.getForObject(u,Map.class);}private void assertConfigured(){if(!configured())throw new IllegalStateException("微信网页授权尚未配置，请配置 AppID、AppSecret 和正式 HTTPS 域名");}private static void fail(Map<String,Object>r){if(r==null||r.containsKey("errcode")&&number(r.get("errcode"))!=0)throw new IllegalStateException("微信接口调用失败："+(r==null?"无响应":value(r,"errmsg")));}private static int number(Object v){return v instanceof Number?((Number)v).intValue():0;}private static String value(Map<String,Object>m,String k){Object v=m.get(k);return v==null?"":String.valueOf(v);}private static String enc(String v){try{return URLEncoder.encode(v,StandardCharsets.UTF_8.name());}catch(Exception e){throw new IllegalStateException(e);}}
}
